# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='demo.Employee'),
        ),
    ]
