web: python manage.py makemigrations && python manage.py migrate && python manage.py loaddata main/fixtures/initial_folder_data.json && python manage.py loaddata main/fixtures/stable_1.0.json && gunicorn therapy.wsgi

