# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
                ('video_date_modified', models.DateTimeField(default=datetime.datetime(2016, 8, 31, 11, 21, 56, 382686, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Video_folder_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Folder')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Video')),
            ],
        ),
    ]
