# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160831_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Folder'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 12, 6, 27, 172853, tzinfo=utc)),
        ),
    ]
