# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160831_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 12, 17, 50, 527000, tzinfo=utc)),
        ),
    ]
