# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160906_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 9, 1, 14, 982793, tzinfo=utc)),
        ),
    ]
