# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160908_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 5, 23, 30, 609034, tzinfo=utc)),
        ),
    ]
