# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapydemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Folders',
        ),
    ]
