# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapydemo', '0002_auto_20160821_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folders',
            new_name='Folder',
        ),
    ]
