# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('therapydemo', '0003_auto_20160821_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
                ('video_date_modified', models.DateTimeField(default=datetime.datetime(2016, 8, 29, 9, 21, 46, 224893, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Video_folder_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='foldername',
            new_name='folder_name',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='folderid',
            new_name='parent_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parentid',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_folder_mapping',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapydemo.Folder'),
        ),
        migrations.AddField(
            model_name='video_folder_mapping',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapydemo.Video'),
        ),
    ]
